name: test_pt_dwidasa_ecommerce_app
description: Simple E-Commerce App on Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  json_annotation: ^4.6.0
  dio: ^5.1.0
  get_it: ^7.2.0
  easy_splash_screen: 1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
